### ISSUE TITLE
角色查询免验证码功能支持

### ISSUE THREAD

**Issue by typenoob** [Witnesscm/Yunzai-plugin#2]
我的角色查询也有验证码，能否添加角色查询免验证码的功能？

**Comment by Witnesscm** [comment]
查询其他角色返回1034验证码是因为ck的原因，无法通过简单的添加device_fp来避免。云崽查询逻辑是从ck池找到使用次数最少的ck来进行查询，如果这个ck很久未刷新过就会返回1034，换成一个比较新的ck来查询就正常，涉及到云崽的ck管理不太好改

这种情况可以考虑使用[loveMys](https://gitee.com/bbaban/loveMys)插件来进行自动或手动过码
