### ISSUE TITLE
请问 cookies 里的 mid 是如何获得的？

### ISSUE THREAD

**Issue by limingxinleo** [Witnesscm/Yunzai-plugin#3]
stuid=${sk.stuid};stoken=${sk.stoken};mid=${sk.mid};

**Comment by Witnesscm** [comment]
手机抓包米游社app，cookie格式就是`stuid=****;stoken=v2****;mid=****;`

或者在浏览器里打开米游社网页，登录后获取cookie，其中的`account_mid_v2`字段

**Comment by limingxinleo** [comment]
我这边测试，mid 随机生成一个就能用。。。
